### ISSUE TITLE
BUG: Dublicate column name

### ISSUE THREAD

**Issue by NikitaPetaichuk** [moevm/mse_db_gen_tasks#76]
**Priority**: High
**Severity**: Critical

При запуске на определённых сидах возникает проблема создания таблиц, в которых дублируются столбцы. Необходимо решить эту проблему.

Пример команды, где происходит падение, и результат выполнения команды:
```shell
mrpedro@mrpedro:~/Programming/Studying/mse_db_gen_tasks$ python3 ./run_gen.py -s 1 -d dump.sql
license_plate
license_plate varchar
country
country varchar
longitude
longitude varchar
company varchar
company
company varchar
time
time varchar
license_plate
license_plate varchar
country
country varchar
longitude
longitude varchar
company varchar
company
company varchar
time
time varchar
Traceback (most recent call last):
  File "/home/mrpedro/Programming/Studying/mse_db_gen_tasks/./run_gen.py", line 30, in <module>
    main()
  File "/home/mrpedro/Programming/Studying/mse_db_gen_tasks/./run_gen.py", line 22, in main
    main_gen.generate_tree(args.seed)
  File "/home/mrpedro/Programming/Studying/mse_db_gen_tasks/main.py", line 19, in generate_tree
    rdb.return_tree()
  File "/home/mrpedro/Programming/Studying/mse_db_gen_tasks/db_gen/classes/random_db_gen_class.py", line 32, in return_tree
    self.tree.loadJSON('db_tree.txt', DbGen('db_f.db'))
  File "/home/mrpedro/Programming/Studying/mse_db_gen_tasks/db_tree/db_tree_class.py", line 39, in loadJSON
    db_generator.create_db_table(self.root.childs[-1].name, len(self.root.childs[-1].data),
  File "/home/mrpedro/Programming/Studying/mse_db_gen_tasks/db_gen/classes/db_gen_class.py", line 14, in create_db_table
    self.db_gen.gen_table(db_file=self.db_file, table_name=table_name, fields=column_names, num=count_of_rows)
  File "/home/mrpedro/.local/lib/python3.9/site-packages/pydbgen/pydbgen.py", line 427, in gen_table
    c.execute(str_create_table)
sqlite3.OperationalError: duplicate column name: time
```

**Comment by esiole** [comment]
Сделано в #90
